### ISSUE TITLE
java.awt.HeadlessException when running command

### ISSUE THREAD

**Issue by julien2424** [imagej/imagej2#302]
Hello!

I'm running a java program where I need to convert to 8-bit, set a gaussian blur, and analyze particles. This is the part of my code that's creating an error:

```
import ij.IJ;
import ij.ImagePlus;

ImagePlus imp = new ImagePlus(path + "original.jpg");
IJ.run( imp, "8-bit", "");
IJ.run( imp, "Gaussian Blur...", "sigma=2" );
IJ.run( imp, "Analyze Particles...", "size=50-Infinity show=Outlines" );
IJ.save( imp, path + "result.jpg");
```

All the IJ.run() lines throw a headless exception error. I'm currently running on the original imagej. I'm willing to change to imagej2, but I couldn't figure out how I would be able to run the same lines using the updated library. 

Could you help me find a solution that works in either imagej or imagej2? All I want my app to do is to retrieve a local image, run the 3 above commands, and save the result image. Thanks!

**Comment by ctrueden** [comment]
@julien2424 It sounds like you are running this on a headless machine—e.g. on a remote server? The original ImageJ does not work headless. ImageJ2 provides limited support for runtime patching the original ImageJ via the [ImageJ Legacy Bridge](https://imagej.net/libs/imagej-legacy) to work in headless mode; however, not all features of the original ImageJ are functional in this mode.

## Getting the program to work

Setting aside the headless issue: the first step is to get your program working _at all_, i.e. in normal mode. As written above, there are a couple of problems:

1. Analyze Particles requires a thresholded image; and
2. Analyze Particles with outlines produces a new image, so saving the original imp won't save the outlined image.

<details><summary>Here is a version of the code that fixes both problems.</summary>

```groovy
import ij.IJ;
import ij.ImagePlus;

path = "/Users/curtis/data/clown8.tif";

ImagePlus imp = new ImagePlus(path);
IJ.run( imp, "8-bit", "");
IJ.run( imp, "Gaussian Blur...", "sigma=2" );
IJ.setAutoThreshold(imp, "Default"); // need to threshold before analyzing particles
outlines = IJ.run( imp, "Analyze Particles...", "size=50-Infinity show=Outlines" );
imp.close();
outlines = IJ.getImage(); // Analyze Particles with outlines produces a new image!
IJ.save( outlines, path + "-outlines.png");
outlines.close();
```

</details>

If you use ImageJ2/Fiji, you can generalize the `path` input using [script parameters](https://imagej.net/scripting/parameters) as follows:

<details><summary>Working version with parameterized path</summary>

```groovy
#@ File path

import ij.IJ;
import ij.ImagePlus;

ImagePlus imp = new ImagePlus(path.getAbsolutePath());
IJ.run( imp, "8-bit", "");
IJ.run( imp, "Gaussian Blur...", "sigma=2" );
IJ.setAutoThreshold(imp, "Default"); // <-- need to threshold before analyzing particles
outlines = IJ.run( imp, "Analyze Particles...", "size=50-Infinity show=Outlines" );
imp.close();
outlines = IJ.getImage(); // Analyze Particles with outlines produces a new image!
IJ.save( outlines, path.getAbsolutePath() + "-outlines.png");
outlines.close();
```

</summary>

If you open the [Script Editor](https://imagej.net/scripting/script-editor) in Fiji, set the language to Groovy, and paste in the above code, you can try it out by clicking the Run button.

## Running it headless

Now let's try it headless. One way to run a script headless with ImageJ2 is described on the [scripting headless](https://imagej.net/scripting/headless) page:

1.  Save the above script as a Groovy script on disk, e.g. `process.groovy`; then
2.  Invoke ImageJ2 on the command line; e.g.:
    ```groovy
    ImageJ-linux64 --ij2 --headless --run ~/Desktop/process.groovy 'path="/home/curtis/data/clown8.tif"'
    ```

And if the script does not invoke any unsupported areas of the original ImageJ, it should run without popping up any graphical elements.

Unfortunately, in my tests, with this particular script, it does not work:

<details><summary>Error log when running this script headless</summary>

```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    ij/gui/NonBlockingGenericDialog.windowActivated(Ljava/awt/event/WindowEvent;)V @23: invokestatic
  Reason:
    Type 'ij/gui/NonBlockingGenericDialog' (current frame, stack[0]) is not assignable to 'java/awt/Window'
  Current Frame:
    bci: @23
    flags: { }
    locals: { 'ij/gui/NonBlockingGenericDialog', 'java/awt/event/WindowEvent' }
    stack: { 'ij/gui/NonBlockingGenericDialog' }
  Bytecode:
    0x0000000: 2bb6 0023 c100 2499 000f 2bb6 0025 2aa5
    0x0000010: 0007 2ab6 0026 2ab8 0027 b1
  Stackmap Table:
    same_frame(@22)

	at ij.plugin.filter.GaussianBlur.showDialog(GaussianBlur.java:86)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:63)
	at ij.IJ.runPlugIn(IJ.java:212)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at ij.IJ.run(IJ.java:323)
	at ij.IJ.run(IJ.java:413)
	at ij.IJ$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
	at Script1.run(Script1.groovy:8)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:303)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:122)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Warning: the fonts "Times" and "Lucida Bright" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
There are no images open
```

</details>

It looks like the `ij.gui.NonBlockingGenericDialog` is not handled correctly by ImageJ2's patching mechanism. There _is_ logic in ImageJ2's patcher to support `NonBlockingGenericDialog` though, so I guess this is a bug in the current code. I suspected it might work better with older versions of the original ImageJ JAR (`ij.jar`), but I tested a few versions including 1.51w, 1.52r, 1.53a, 1.53d, and 1.53f, and they all suffer from this problem, so it may be a regression in the `ij1-patcher` or `imagej-legacy` libraries.

## Avoiding the headless-unfriendly calls

OK, so maybe we can use ImageJ2's API in places where the original ImageJ API is not working headless. The [ImageJ Ops](https://imagej.net/libs/imagej-ops) library has Gaussian blur, autothresholding, and connected component analysis, all of which might be useful here.

I worked up a hybrid Groovy script (written in as Java-ish a way as possible, so that the syntax is nearly identical to valid Java code), which successfully outlines an input image, writing out the result to an output image. I hope this is what you were looking for.

<details><summary>outline-headless-with-ops.groovy</summary>

```groovy
#@ ImageJ ij
#@ File file

String path = file.getAbsolutePath();

// Open the requested image as an ImageJ2 Dataset.
import net.imagej.Dataset;
Dataset image = ij.scifio().datasetIO().open(path);

// Apply a Gaussian blur with sigma of 2.
blurred = ij.op().filter().gauss(image, 2);

// Binarize the image with the Otsu algorithm.
thresholded = ij.op().threshold().otsu(blurred);

// Chop up the binary image into connected regions.
import static net.imglib2.algorithm.labeling.ConnectedComponents.StructuringElement;
cca = ij.op().labeling().cca(thresholded, StructuringElement.EIGHT_CONNECTED);

// Convert each region into a polygon, since we want outlines.
// And filter out any regions that are too small.
// Add whatever other filtering you want here, to select only desired regions.
import java.util.ArrayList;
import net.imglib2.roi.labeling.LabelRegion;
import net.imglib2.roi.labeling.LabelRegions;
import net.imglib2.roi.geom.real.Polygon2D;
LabelRegions labelRegions = new LabelRegions(cca);
ArrayList<Polygon2D> regions = new ArrayList<>();
for (LabelRegion labelRegion in labelRegions) { // Java: replace "in" with colon symbol.
	Polygon2D region = ij.convert().convert(labelRegion, Polygon2D.class);
	double size = ij.op().geom().size(region).get();
	if (size >= 50) regions.add(region); // ROI is large enough to keep.
}

// Now, back to the world of the original ImageJ!
import ij.IJ;
import ij.ImagePlus;
import ij.gui.Overlay;
import ij.gui.Roi;

// Make an original-ImageJ-style Overlay from our list of regions.
Overlay overlay = new Overlay();
for (Polygon2D region in regions) { // Java: replace "in" with colon symbol.
	// Convert ImgLib2-style ROI to ImageJ-style ROI.
	Roi roi = ij.convert().convert(region, Roi.class);
	overlay.add(roi);
}

// Convert the ImageJ2-style image into an original ImageJ image.
ImagePlus imp = ij.convert().convert(image, ImagePlus.class);
imp.setDisplayRange(0, 255); // If your data is not 8-bit, you need to decide on the display range.

// Attach the overlay to the ImagePlus, and bake it in.
imp.setOverlay(overlay);
ImagePlus flattened = imp.flatten();

// Finally, save the completed ImagePlus to disk.
String outputPath = path + "-outlines.png";
IJ.saveAs(flattened, "PNG", outputPath);

println("Result saved to: " + outputPath); // Java: change to System.out.println
```

</details>

It uses ImageJ Ops for the image processing parts, and then uses the original ImageJ API to paint the resultant regions onto an `ImagePlus`, because ImageJ2/ImgLib2's support for painting ROIs is not yet as accessible as with the original ImageJ.

Let me know if you have any questions about it!

**Comment by aubreyyan** [comment]
so @julien2424 what I'm hearing is that what you're attempting to do is indeed possible?

**Comment by aubreyyan** [comment]
@ctrueden sorry to bother you, but we tried to transfer over the script to the best of our ability and we're running into odd behavior:

![image](https://user-images.githubusercontent.com/60039494/156042936-5622b8ee-6ce6-4e60-bccb-0f9f5699c84c.png)

When our script gets to the line `ImagePlus imp = ij.convert().convert(image, ImagePlus.class);`, the return value of `ij.convert().convert` becomes null, because of the screenshot posted above.

Do you have any idea why this might be happening? Happy to create a minimally reproducible example if you want
